name: test
on:
    pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test1
        run: echo '${{ toJSON(github) }}'
      - name: test2
        run: echo '${{ toJSON(github.event.pullrequest.user) }}'
      - name: test3
        run: echo '${{ github.event.pull_request.user.login }}'
      - name: test4
        run: echo '${{ toJSON(github.event.pull_request.base.user) }}'
      - name: test5
        run: echo '${{ github.event.pull_request.base.user.login }}'