name: test
on:
    pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test1
        run: echo '${{ toJSON(github) }}'
      - name: test2
        run: echo '${{ toJSON(github.user) }}'
      - name: test3
        run: echo '${{ github.user.login }}'
      - name: test4
        run: echo '${{ toJSON(github.base.user) }}'
      - name: test5
        run: echo '${{ github.base.user.login }}'